version: "1"
rules:
  - base: master-clean
    upstream: MultiMC:master
    mergeMethod: merge
    mergeUnstable: false
  - base: master-clean-arm32
    upstream: MultiMC:master
    mergeMethod: merge
    mergeUnstable: false
