name: Update Repo

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-repo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: testing

      # Runs a set of commands using the runners shell
      - name: Run app update scripts
        run: |
          git remote add -f upstream "https://github.com/MultiMC/meta-multimc.git"
          git remote -v
          git branch --all
          git config --list
          git config user.email "28281419+theofficialgman@users.noreply.github.com"
          git config user.name "theofficialgman"
          git checkout testing
          git merge upstream/master
          git push 
